In [1]:
import numpy as np

# Example 1

In [2]:
N = 1000000
A = np.random.rand(N)
B = np.random.rand(N)

In [3]:
%%time
C = np.zeros(N)

for i in range(N):
    C[i] = A[i] + B[i]

print(sum(C))

1000115.5661692542
CPU times: user 599 ms, sys: 7.2 ms, total: 606 ms
Wall time: 606 ms


In [4]:
%%time
C = A + B

print(sum(C))

1000115.5661692542
CPU times: user 84.1 ms, sys: 4.02 ms, total: 88.2 ms
Wall time: 86.6 ms


# Basic Operations

In [5]:
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [6]:
# Select index
A[1]

2

In [7]:
# Select range
A[1:4]

array([2, 3, 4])

In [8]:
# Update all elements
A + 1

array([2, 3, 4, 5])

In [9]:
# Square all elements (3**2 = 3 * 3)
A ** 2

array([ 1,  4,  9, 16])

In [10]:
# Will raise errors if Vectors are not the same length
np.array([1,2,3]) + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

# Example 2

In [11]:
N = 1000000
A = np.random.randint(2, size=N)

In [12]:
%%time
C = 0

for i in range(N-1):
    x = A[i]
    y = A[i+1]

    if x == 1 and y == 1:
        C += 1
        
print(C)

249655
CPU times: user 754 ms, sys: 6.09 ms, total: 760 ms
Wall time: 762 ms


In [13]:
%%time
C = A[:-1] * A[1:] 
print(sum(C))

249655
CPU times: user 82.8 ms, sys: 3.19 ms, total: 86 ms
Wall time: 85 ms


# Few More Operations

In [14]:
A = np.array([1,2,3,4])

In [15]:
# Comparison
A > 2

array([False, False,  True,  True])

In [16]:
# Selecting / Filtering items based on a comparison
A[A > 2]

array([3, 4])

In [17]:
# Turn off values that do not match comparison (This works because True=1 and False=0)
A * (A > 2)

array([0, 0, 3, 4])

In [18]:
# Python doesn't have explicit types so these are the same
np.array([1,2,3,4]) * np.array([0,0,1,1])

array([0, 0, 3, 4])

In [19]:
N = 1000000
A = np.random.rand(N)

In [20]:
%%time
X = A[A > 0.5]

print(len(X))

498708
CPU times: user 8.92 ms, sys: 3.34 ms, total: 12.3 ms
Wall time: 10.3 ms


In [21]:
%%time

X = []
for i in range(N):
    if A[i] > 0.5:
        X.append(A[i])
        
print(len(X))

498708
CPU times: user 439 ms, sys: 12.8 ms, total: 451 ms
Wall time: 453 ms


# Example 3

In [22]:
N = 1000000
A = np.random.rand(N)

In [23]:
%%time
C = np.zeros(N)

for i in range(N):
    if A[i] > 0.5:
        C[i] = A[i] * 2
    else:
        C[i] = A[i] * 3
        

print(sum(C))

1124834.3677210268
CPU times: user 865 ms, sys: 4.11 ms, total: 869 ms
Wall time: 869 ms


In [24]:
%%time
D = A > 0.5

C = (A * D * 2) + (A * ~D * 3)

print(sum(C))

1124834.3677210268
CPU times: user 93.5 ms, sys: 5.41 ms, total: 98.9 ms
Wall time: 97 ms


# Matrix

In [25]:
M = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
])

In [26]:
# 2D Matrix made up of vectors
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
# An entire Row
M[0]

array([1, 2, 3, 4])

In [28]:
# An entire column
M[:,0]

array([ 1,  5,  9, 13])

In [29]:
# Vectors can go in either direction
# And the matrix can be can be rotated

M.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [30]:
# You can make a vector out the diaganal
M.diagonal()

array([ 1,  6, 11, 16])